[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
# eth-rpc-url = "<your rpc url here>"
# etherscan-api-key = "< >"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config